import type { MeterRecord } from "./types";

export const SAMPLE_RECORDS: MeterRecord[] = [
  {
    id: "a-1",
    scala: "A",
    appartamento: "1",
    codiceContatore: "CTR-A-101",
    intestatario: "Rossi Mario",
    letturaPrecedente: 12450,
    nuovaLettura: null,
  },
  {
    id: "a-2",
    scala: "A",
    appartamento: "2",
    codiceContatore: "CTR-A-102",
    intestatario: "Bianchi Laura",
    letturaPrecedente: 8920,
    nuovaLettura: null,
  },
  {
    id: "a-3",
    scala: "A",
    appartamento: "3",
    codiceContatore: "CTR-A-103",
    letturaPrecedente: 15670,
    nuovaLettura: null,
  },
  {
    id: "b-1",
    scala: "B",
    appartamento: "1",
    codiceContatore: "CTR-B-201",
    intestatario: "Verdi Giuseppe",
    letturaPrecedente: 21030,
    nuovaLettura: null,
  },
  {
    id: "b-2",
    scala: "B",
    appartamento: "2",
    codiceContatore: "CTR-B-202",
    intestatario: "Neri Anna",
    letturaPrecedente: 7450,
    nuovaLettura: null,
  },
  {
    id: "c-1",
    scala: "C",
    appartamento: "1",
    codiceContatore: "CTR-C-301",
    intestatario: "Ferrari Luca",
    letturaPrecedente: 18900,
    nuovaLettura: null,
  },
  {
    id: "c-2",
    scala: "C",
    appartamento: "2",
    codiceContatore: "CTR-C-302",
    letturaPrecedente: 11200,
    nuovaLettura: null,
  },
  {
    id: "c-3",
    scala: "C",
    appartamento: "3",
    codiceContatore: "CTR-C-303",
    intestatario: "Colombo Sara",
    letturaPrecedente: 9340,
    nuovaLettura: null,
  },
];
